<script setup lang="ts"></script>

<template>
  <section class="about">
    <div class="container">
      <h2 class="title">About me:</h2>
      <p class="text">
        My son is a talented frontend developer specializing in JavaScript, Vue 3,
        Nuxt, and TypeScript. Every morning he starts with a piece of banana and a
        cup of aromatic tea with cookies that he loves. He creates quality and
        accessible code that is convenient for users and colleagues. Work is his
        calling, and he always strives to be the best in his field. If you are
        looking for a reliable and experienced developer, my son is always ready
        to help you with your project.
      </p>
      <div class="description">
        <span class="subtitle">"Generated by chatGPT"</span>
        <br>
        <span class="subtitle">"Generated by my dad"</span>
      </div>
    </div>
  </section>
</template>

<style scoped>
  .about {
    width: 600px;
    text-align: start;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
  }

  .title {
    text-align: center;
    margin-bottom: 10px;
    font-size: 26px;
  }

  .text {
    font-size: 17px;
  }

  .description {
    margin-top: 15px;
  }

  .subtitle {
    color: #999999;
    position: relative;
  }

  .subtitle:first-child {
    text-decoration: line-through;
  }
</style>
